import { StyleSheet } from 'react-native';
import { colors, spacing, borderRadius, fontSize, fontWeight, shadows, zIndex, dimensions } from '../constants/theme';

// Reusable style fragments
const buttonTextBase = {
  color: colors.textWhite,
  fontSize: fontSize.sm + 1,
  fontWeight: fontWeight.medium,
  letterSpacing: 0.3,
};

const smallButtonBase = {
  paddingHorizontal: 14,
  paddingVertical: 8,
  borderRadius: borderRadius.xs,
  flexDirection: 'row',
  alignItems: 'center',
  gap: spacing.sm,
  boxShadow: shadows.sm,
  elevation: 2,
};

const cardBorderBase = {
  borderWidth: 2,
  borderColor: colors.primary,
  borderStyle: 'solid',
};

export const styles = StyleSheet.create({
  // Layout
  scrollContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    minHeight: '100%',
    paddingBottom: 100,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: 140,
    paddingBottom: 100,
    paddingLeft: '5%',
    paddingRight: '5%',
  },
  contentArea: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.xl,
    height: dimensions.cardHeight,
    maxWidth: 1000,
    width: '100%',
    marginHorizontal: 'auto',
    marginBottom: 30,
    justifyContent: 'center',
  },
  contentAreaFullWidth: {
    maxWidth: 1000,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Navigation
  navArea: {
    position: 'fixed',
    top: '50vh',
    marginTop: -40,
    width: '5%',
    minWidth: 50,
    height: 80,
    zIndex: zIndex.fixed,
    justifyContent: 'center',
    alignItems: 'center',
    pointerEvents: 'auto',
    touchAction: 'auto',
  },
  navAreaLeft: {
    left: 0,
  },
  navAreaRight: {
    right: 0,
  },
  navArrow: {
    fontSize: 60,
    color: '#333',
    fontWeight: fontWeight.light,
    opacity: 0.5,
    textShadow: '0 2px 4px rgba(0,0,0,0.2)',
  },

  // Card Container
  cardContainer: {
    height: dimensions.cardHeight,
    width: dimensions.cardWidth,
    position: 'relative',
  },
  cardHeader: {
    position: 'absolute',
    top: -110,
    left: 0,
    right: 0,
    zIndex: zIndex.sticky,
    alignItems: 'center',
    minHeight: 100,
  },
  cardHeaderTitle: {
    fontSize: fontSize.xxxl,
    fontWeight: fontWeight.light,
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: spacing.lg,
    letterSpacing: -1.5,
    textShadow: '0 2px 4px rgba(0, 0, 0, 0.05)',
  },
  cardHeaderDescription: {
    fontSize: fontSize.lg + 1,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 26,
    paddingHorizontal: 40,
    fontWeight: fontWeight.light,
    maxWidth: 600,
    marginHorizontal: 'auto',
    textShadow: '0 1px 2px rgba(0, 0, 0, 0.03)',
  },

  // Header Buttons
  headerButtons: {
    position: 'absolute',
    top: 0,
    right: 0,
    flexDirection: 'row',
    gap: spacing.xl,
    zIndex: 30,
    alignItems: 'center',
  },
  headerButton: {
    padding: spacing.sm,
    opacity: 0.7,
    transition: 'opacity 0.2s',
  },
  headerUserInfo: {
    backgroundColor: colors.overlayLight,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm - 2,
    borderRadius: borderRadius.xs,
  },
  headerUserInfoText: {
    color: colors.textWhite,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.normal,
  },
  headerLogoutButton: {
    ...smallButtonBase,
    backgroundColor: colors.textMuted,
  },
  headerLoginButton: {
    ...smallButtonBase,
    backgroundColor: colors.primary,
  },
  // Shared button text style
  headerButtonText: buttonTextBase,
  headerLogoutButtonText: buttonTextBase,
  headerLoginButtonText: buttonTextBase,

  // Toggle Switch
  toggleSwitch: {
    width: 32,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.textSecondary,
    position: 'relative',
    transition: 'background-color 0.2s',
  },
  toggleSwitchActive: {
    backgroundColor: colors.primary,
  },
  toggleKnob: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: colors.textWhite,
    position: 'absolute',
    top: 2,
    left: 2,
    transition: 'left 0.2s',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.2)',
  },
  toggleKnobActive: {
    left: 16,
  },

  // Cards
  card: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backfaceVisibility: 'hidden',
    borderRadius: borderRadius.md,
    backgroundColor: colors.backgroundSemiTransparent,
    boxShadow: shadows.lg,
    elevation: 4,
    overflow: 'visible',
    ...cardBorderBase,
    backdropFilter: 'blur(10px)',
  },
  cardBack: {
    backgroundColor: colors.backgroundSemiTransparent,
    ...cardBorderBase,
    backdropFilter: 'blur(10px)',
  },
  gardenBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: borderRadius.sm,
    overflow: 'hidden',
  },
  grassPattern: {
    flex: 1,
    backgroundColor: '#b8c5a0',
    backgroundImage: 'repeating-linear-gradient(0deg, transparent, transparent 49px, rgba(0,0,0,0.12) 49px, rgba(0,0,0,0.12) 50px), repeating-linear-gradient(90deg, transparent, transparent 49px, rgba(0,0,0,0.12) 49px, rgba(0,0,0,0.12) 50px)',
    backgroundSize: '50px 50px',
    opacity: 0.3,
    borderRadius: borderRadius.sm,
  },
  stoneWall: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderWidth: 0,
    borderColor: 'transparent',
    borderStyle: 'solid',
    opacity: 0,
    borderRadius: borderRadius.sm,
  },
  backgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: borderRadius.sm,
    overflow: 'hidden',
  },
  backgroundImageStyle: {
    borderRadius: borderRadius.sm,
  },
  imageOverlay: {
    flex: 1,
    backgroundColor: 'rgba(232, 237, 224, 0.75)',
    borderRadius: borderRadius.sm,
  },

  // Empty/Add Cards
  emptyCard: {
    flex: 1,
    position: 'relative',
  },
  emptyContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addCard: {
    flex: 1,
    position: 'relative',
  },
  addContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  plusButton: {
    fontSize: 72,
    color: colors.primary,
    marginBottom: spacing.lg,
    fontWeight: fontWeight.light,
  },
  // Shared empty text style
  emptyText: {
    fontSize: fontSize.xl,
    color: colors.textSecondary,
    fontWeight: fontWeight.light,
    letterSpacing: 0,
  },
  addCardText: {
    fontSize: fontSize.xl,
    color: colors.textSecondary,
    fontWeight: fontWeight.light,
    letterSpacing: 0,
  },
  gardenCard: {
    flex: 1,
    position: 'relative',
  },

  // Form
  formContent: {
    padding: spacing.xxxl,
    paddingBottom: 40,
    flex: 1,
  },
  formTitle: {
    fontSize: 28,
    fontWeight: fontWeight.light,
    color: colors.textPrimary,
    marginBottom: spacing.xxl,
    letterSpacing: -0.5,
  },
  label: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    color: colors.textMuted,
    marginBottom: spacing.sm - 2,
    marginTop: spacing.md,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  input: {
    backgroundColor: colors.backgroundLight,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: borderRadius.xs,
    padding: spacing.md,
    fontSize: fontSize.lg,
    color: colors.textPrimary,
    outlineWidth: 0,
  },
  textArea: {
    height: 70,
    textAlignVertical: 'top',
  },
  formButtons: {
    flexDirection: 'row',
    marginTop: spacing.xxl,
    gap: spacing.lg,
  },
  button: {
    flex: 1,
    padding: 14,
    borderRadius: borderRadius.xs,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: '#f0f0f0',
  },
  saveButton: {
    backgroundColor: colors.primary,
    boxShadow: shadows.sm,
    elevation: 2,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonText: {
    color: colors.textWhite,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.medium,
    letterSpacing: 0.3,
  },

  // Indicator
  indicator: {
    position: 'fixed',
    top: 30,
    left: '5%',
    backgroundColor: colors.overlayLight,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.xs,
    minWidth: 100,
    alignItems: 'center',
  },
  indicatorText: {
    color: colors.textWhite,
    fontSize: fontSize.sm + 1,
    fontWeight: fontWeight.normal,
    letterSpacing: 0.5,
  },

  // Modal
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.overlayDark,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: zIndex.modal,
  },
  modalContent: {
    backgroundColor: colors.backgroundWhite,
    borderRadius: borderRadius.lg,
    padding: spacing.xxxl,
    width: '90%',
    maxWidth: 420,
    boxShadow: shadows.xl,
    elevation: 12,
    backdropFilter: 'blur(10px)',
  },
  modalTitle: {
    fontSize: fontSize.xxl,
    fontWeight: fontWeight.light,
    color: colors.textPrimary,
    marginBottom: spacing.md,
    letterSpacing: -0.5,
  },
  modalMessage: {
    fontSize: fontSize.lg,
    color: colors.textSecondary,
    marginBottom: 28,
    lineHeight: 22,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.xl,
  },
  modalButton: {
    flex: 1,
    padding: 14,
    borderRadius: borderRadius.xs,
    alignItems: 'center',
  },
  modalCancelButton: {
    backgroundColor: '#f0f0f0',
  },
  modalCancelButtonText: {
    color: colors.textSecondary,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.medium,
    letterSpacing: 0.3,
  },
  modalDeleteButton: {
    backgroundColor: colors.danger,
    boxShadow: shadows.sm,
    elevation: 2,
  },
  modalSaveButton: {
    backgroundColor: colors.primary,
    boxShadow: shadows.sm,
    elevation: 2,
  },
  modalButtonText: {
    color: colors.textWhite,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.medium,
    letterSpacing: 0.3,
  },

  // Photo Modal
  photoViewModalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: zIndex.modal,
  },
  photoViewModalContent: {
    backgroundColor: 'transparent',
    borderRadius: borderRadius.lg,
    padding: 0,
    width: 'auto',
    maxWidth: 600,
    maxHeight: 600,
    position: 'relative',
    overflow: 'visible',
  },
  photoModalCloseOutside: {
    position: 'absolute',
    top: -spacing.xxl,
    right: -spacing.xxl,
    zIndex: zIndex.modal + 1,
    cursor: 'pointer',
    width: 56,
    height: 56,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    borderRadius: borderRadius.round,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.primary,
    borderStyle: 'solid',
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.3)',
  },
  photoViewImage: {
    width: 'auto',
    height: 'auto',
    maxWidth: 600,
    maxHeight: 600,
    objectFit: 'contain',
    display: 'block',
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.primary,
    borderStyle: 'solid',
  },
  photoModalLoading: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  photoModalContent: {
    backgroundColor: colors.backgroundWhite,
    borderRadius: borderRadius.lg,
    padding: spacing.xxxl,
    width: '90%',
    maxWidth: 500,
    boxShadow: shadows.xl,
    elevation: 12,
    backdropFilter: 'blur(10px)',
    position: 'relative',
  },
  photoModalClose: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.md,
    width: 32,
    height: 32,
    backgroundColor: colors.primary,
    borderRadius: borderRadius.round,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: zIndex.dropdown,
  },
  photoModalDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: spacing.xl,
  },
  photoModalDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.borderLight,
  },
  photoModalDividerText: {
    paddingHorizontal: spacing.md,
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
  },
  photoDropZone: {
    borderWidth: 2,
    borderColor: colors.primaryMedium,
    borderStyle: 'dashed',
    borderRadius: borderRadius.md,
    padding: spacing.xxxl,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryLight,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  photoDropZoneDragging: {
    backgroundColor: colors.primaryMedium,
    borderColor: colors.primary,
  },
  photoDropZoneLabel: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: spacing.md,
    cursor: 'pointer',
  },
  photoDropZoneText: {
    fontSize: fontSize.md,
    color: colors.primary,
    fontWeight: fontWeight.medium,
    textAlign: 'center',
  },
  photoPreviewContainer: {
    marginTop: spacing.xl,
    marginBottom: spacing.md,
    minHeight: 200,
    maxHeight: 400,
    borderRadius: borderRadius.md,
    overflow: 'hidden',
    backgroundColor: colors.backgroundLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoPreview: {
    width: '100%',
    height: '100%',
    minHeight: 200,
    maxHeight: 400,
  },
  photoNoPreviewText: {
    fontSize: fontSize.lg,
    color: colors.textMuted,
    fontStyle: 'italic',
  },

  // Undo/Logout Buttons
  undoButton: {
    position: 'fixed',
    top: 30,
    right: '5%',
    backgroundColor: colors.primary,
    ...smallButtonBase,
    zIndex: zIndex.dropdown,
  },
  undoButtonText: buttonTextBase,
  logoutButton: {
    position: 'fixed',
    top: 30,
    right: 'calc(5% + 120px)',
    backgroundColor: colors.textMuted,
    ...smallButtonBase,
    zIndex: zIndex.dropdown,
  },
  logoutButtonText: buttonTextBase,
  loginButtonViewer: {
    position: 'fixed',
    top: 30,
    right: '5%',
    backgroundColor: colors.primary,
    ...smallButtonBase,
    zIndex: zIndex.dropdown,
  },
  loginButtonViewerText: buttonTextBase,
  userInfo: {
    position: 'fixed',
    top: 70,
    right: 'calc(5% + 120px)',
    backgroundColor: colors.overlayLight,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm - 2,
    borderRadius: borderRadius.xs,
    zIndex: zIndex.dropdown,
  },
  userInfoText: {
    color: colors.textWhite,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.normal,
  },

  // Tree Edit Card
  treeEditCard: {
    position: 'absolute',
    left: 50,
    top: 0,
    borderRadius: borderRadius.lg,
    padding: spacing.sm,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    width: dimensions.treeEditCardWidth,
    maxWidth: dimensions.treeEditCardWidth,
    backgroundColor: colors.backgroundTransparent,
    boxShadow: shadows.xl,
    elevation: 12,
    ...cardBorderBase,
    backdropFilter: 'blur(10px)',
    overflow: 'visible',
    boxSizing: 'border-box',
  },
  treeEditCardWithButton: {
    paddingRight: 42,
  },
  treeEditField: {
    marginBottom: spacing.sm - 2,
  },
  treeEditLabel: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.medium,
    color: colors.textMuted,
    marginBottom: 3,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  treeEditInput: {
    backgroundColor: colors.backgroundLight,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: borderRadius.xs,
    padding: spacing.sm - 2,
    fontSize: fontSize.md,
    color: colors.textPrimary,
  },
  treeEditReadOnly: {
    backgroundColor: 'transparent',
    padding: spacing.sm - 2,
    fontSize: fontSize.md,
    color: colors.textPrimary,
    fontWeight: fontWeight.normal,
  },
  treeAge: {
    fontSize: fontSize.md,
    color: colors.textPrimary,
    fontWeight: fontWeight.normal,
    marginTop: 2,
    textAlign: 'left',
    padding: spacing.sm - 2,
  },
  treeEditFieldHorizontal: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xs,
    gap: 2,
    paddingVertical: 1,
    maxWidth: '100%',
  },
  treeEditLabelHorizontal: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    color: colors.primary,
    minWidth: 60,
    flexShrink: 0,
    letterSpacing: 0.3,
  },
  treeEditValueHorizontal: {
    fontSize: fontSize.md,
    color: colors.textPrimary,
    fontWeight: fontWeight.medium,
    width: dimensions.inputWidth,
  },
  treeEditInputHorizontal: {
    backgroundColor: 'rgba(250, 250, 250, 0.8)',
    borderWidth: 1,
    borderColor: colors.primaryMedium,
    borderRadius: borderRadius.sm,
    padding: spacing.xs,
    fontSize: fontSize.md,
    color: colors.textPrimary,
    width: dimensions.inputWidth,
    maxWidth: dimensions.inputWidth,
    height: 28,
    transition: 'all 0.2s ease',
    boxSizing: 'border-box',
  },

  // Buy Button
  buyButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.xs,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm - 2,
    marginTop: spacing.md,
    boxShadow: shadows.sm,
    elevation: 2,
  },
  buyButtonText: {
    color: colors.textWhite,
    fontSize: fontSize.md,
    fontWeight: fontWeight.medium,
    letterSpacing: 0.3,
  },
  buyButtonSquare: {
    width: 32,
    height: 32,
    backgroundColor: colors.primary,
    borderRadius: borderRadius.md,
    justifyContent: 'center',
    alignItems: 'center',
    boxShadow: '0 4px 12px rgba(85, 107, 47, 0.3), 0 2px 4px rgba(0, 0, 0, 0.1)',
    elevation: 4,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  photoButtonSquare: {
    width: 32,
    height: 32,
    backgroundColor: colors.primary,
    borderRadius: borderRadius.md,
    justifyContent: 'center',
    alignItems: 'center',
    boxShadow: '0 4px 12px rgba(85, 107, 47, 0.3), 0 2px 4px rgba(0, 0, 0, 0.1)',
    elevation: 4,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  photoButtonSquareDisabled: {
    backgroundColor: colors.textMuted,
    opacity: 0.5,
    cursor: 'not-allowed',
  },

  // Items Panel
  itemsPanelToggle: {
    position: 'absolute',
    right: spacing.xl,
    top: '50%',
    marginTop: -30,
    width: 40,
    height: 60,
    backgroundColor: colors.textWhite,
    borderTopLeftRadius: borderRadius.lg,
    borderBottomLeftRadius: borderRadius.lg,
    justifyContent: 'center',
    alignItems: 'center',
    boxShadow: '-2px 0 8px rgba(0, 0, 0, 0.1)',
    elevation: 4,
    zIndex: zIndex.fixed,
  },
  itemsPanel: {
    width: dimensions.itemsPanelWidth,
    height: '100%',
    borderRadius: borderRadius.md,
    boxShadow: shadows.lg,
    elevation: 4,
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
  },
  itemsPanelHeader: {
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  itemsPanelTitle: {
    fontSize: 14,
    fontWeight: fontWeight.medium,
    color: colors.textPrimary,
    letterSpacing: 0,
  },
  itemsPanelScroll: {
    flex: 1,
    overflow: 'hidden',
  },
  itemCategory: {
    padding: spacing.md - 2,
    borderBottomWidth: 1,
    borderBottomColor: colors.backgroundLight,
  },
  categoryTitle: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.medium,
    color: colors.textMuted,
    marginBottom: spacing.sm - 2,
    letterSpacing: 1.5,
  },
  categoryTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm - 2,
  },
  generateButtonSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.primaryLight,
    borderRadius: borderRadius.xs,
    borderWidth: 1,
    borderColor: colors.primaryMedium,
  },
  generateButtonSmallText: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.medium,
    color: colors.primary,
    letterSpacing: 0.5,
  },

  // Items Grid
  itemsGrid: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    justifyContent: 'flex-start',
  },
  itemCard: {
    width: 64,
    minWidth: 64,
    maxWidth: 64,
    height: 64,
    backgroundColor: '#f5f5f5',
    borderRadius: borderRadius.xs,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xs,
    borderWidth: 1,
    borderColor: 'rgba(85, 107, 47, 0.08)',
    cursor: 'grab',
    userSelect: 'none',
    boxSizing: 'border-box',
    touchAction: 'none',
    boxShadow: '0 2px 6px rgba(0, 0, 0, 0.06)',
    transition: 'all 0.2s ease',
  },
  itemIcon: {
    fontSize: 26,
    marginBottom: 2,
  },
  itemImage: {
    width: 32,
    height: 32,
    marginBottom: 2,
  },
  itemName: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    textAlign: 'center',
    fontWeight: fontWeight.normal,
  },

  // Dropped Items
  droppedItem: {
    position: 'absolute',
    width: dimensions.droppedItemSize,
    height: dimensions.droppedItemSize,
    transform: 'translate(-50%, -50%)',
    zIndex: zIndex.dropdown,
    cursor: 'pointer',
    userSelect: 'none',
    touchAction: 'none',
    borderRadius: dimensions.droppedItemSize / 2,
    borderWidth: 1,
    borderColor: colors.borderMedium,
    borderStyle: 'solid',
    backgroundColor: colors.background,
    boxShadow: shadows.md,
    elevation: 8,
  },
  droppedItemEditing: {
    borderColor: colors.primary,
    borderWidth: 2,
    boxShadow: shadows.primaryGlow,
    zIndex: zIndex.sticky,
  },
  droppedItemDimmed: {
    opacity: 0.25,
    filter: 'grayscale(90%)',
  },
  droppedItemDragging: {
    opacity: 0.3,
  },
  droppedItemIcon: {
    fontSize: fontSize.lg + 1,
    textAlign: 'center',
  },
  droppedItemImage: {
    width: dimensions.droppedItemSize,
    height: dimensions.droppedItemSize,
  },
  removeItemButton: {
    position: 'absolute',
    top: -10,
    right: -10,
    width: 14,
    height: 14,
    backgroundColor: colors.danger,
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.2)',
    elevation: 2,
  },
  removeItemText: {
    color: colors.textWhite,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    lineHeight: 10,
  },
  editAvatarButton: {
    position: 'absolute',
    bottom: -10,
    left: -10,
    width: 14,
    height: 14,
    backgroundColor: colors.textMuted,
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.2)',
    elevation: 2,
  },

  // Drop Indicator
  dropIndicator: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: borderRadius.md,
    borderWidth: 2,
    borderColor: colors.primary,
    borderStyle: 'dashed',
  },
  dropIndicatorText: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.light,
    color: colors.primary,
    letterSpacing: 0,
  },

  // Available Toggle
  availableToggleContainer: {
    marginHorizontal: 'auto',
    maxWidth: 1000,
    width: '90%',
    marginBottom: spacing.md,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  availableToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.sm,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.textWhite,
    borderRadius: borderRadius.xs,
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.08)',
    cursor: 'pointer',
  },
  availableToggleText: {
    fontSize: 14,
    color: colors.textPrimary,
    fontWeight: fontWeight.normal,
  },

  // Trees Table
  treesTable: {
    position: 'relative',
    marginHorizontal: 'auto',
    maxWidth: 1000,
    width: '90%',
    borderRadius: borderRadius.md,
    backgroundColor: colors.backgroundTransparent,
    boxShadow: shadows.xl,
    overflow: 'visible',
    marginBottom: 40,
    ...cardBorderBase,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: colors.primaryDark,
    padding: spacing.md,
    borderTopLeftRadius: borderRadius.sm,
    borderTopRightRadius: borderRadius.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.primaryMedium,
  },
  tableHeaderCell: {
    justifyContent: 'center',
  },
  tableHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: spacing.sm,
  },
  tableHeaderSortButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  tableHeaderText: {
    color: colors.textWhite,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  tableSortIcon: {
    color: colors.textWhite,
    fontSize: 14,
    fontWeight: fontWeight.normal,
    marginLeft: 2,
  },

  // Filter Dropdown
  filterDropdown: {
    position: 'absolute',
    top: 50,
    backgroundColor: colors.backgroundSemiTransparent,
    ...cardBorderBase,
    borderRadius: borderRadius.md,
    boxShadow: shadows.xl,
    maxHeight: 300,
    minWidth: 200,
    maxWidth: 300,
    zIndex: zIndex.modal,
    backdropFilter: 'blur(12px)',
    WebkitBackdropFilter: 'blur(12px)',
  },
  filterDropdownHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: spacing.sm,
    gap: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(85, 107, 47, 0.2)',
  },
  filterButton: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm - 2,
    backgroundColor: colors.primary,
    borderRadius: borderRadius.xs,
    flex: 1,
    alignItems: 'center',
    whiteSpace: 'nowrap',
  },
  filterButtonText: {
    color: colors.textWhite,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    whiteSpace: 'nowrap',
  },
  filterDropdownScroll: {
    maxHeight: 250,
  },
  filterOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.md - 2,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(85, 107, 47, 0.1)',
    gap: spacing.md - 2,
    minHeight: 40,
  },
  filterOptionText: {
    fontSize: fontSize.md,
    color: colors.textPrimary,
    flex: 1,
  },

  // Table Rows
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(85, 107, 47, 0.15)',
    padding: spacing.md,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  tableRowEven: {
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  tableRowSelected: {
    backgroundColor: '#d4e5c9',
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
  },
  tableCell: {
    fontSize: fontSize.md,
    color: colors.textPrimary,
  },
  tableCellSmall: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
  },
  tableCheckboxCell: {
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxContainer: {
    padding: spacing.xs,
  },

  // Table Columns
  columnType: { flex: 2 },
  columnSort: { flex: 2 },
  columnYear: { flex: 1 },
  columnAge: { flex: 1 },
  columnOwner: { flex: 1 },
  columnStatus: { flex: 1 },
  columnPhoto: { flex: 0.5, justifyContent: 'center', alignItems: 'center' },

  emptyTableText: {
    padding: spacing.xl,
    textAlign: 'center',
    color: colors.textMuted,
    fontSize: fontSize.md,
  },

  // Tooltip
  tooltipContainer: {
    position: 'relative',
    display: 'inline-block',
  },
  tooltipContent: {
    position: 'absolute',
    bottom: '100%',
    left: '50%',
    transform: 'translateX(-50%)',
    marginBottom: spacing.sm,
    backgroundColor: colors.primary,
    paddingVertical: spacing.sm - 2,
    paddingHorizontal: spacing.md - 2,
    borderRadius: borderRadius.xs,
    whiteSpace: 'nowrap',
    zIndex: zIndex.modal,
    pointerEvents: 'none',
  },
  tooltipContentTop: {
    bottom: 'auto',
    top: '100%',
    marginBottom: 0,
    marginTop: spacing.sm,
  },
  tooltipText: {
    color: colors.textWhite,
    fontSize: fontSize.sm + 1,
  },
  tooltipArrow: {
    position: 'absolute',
    bottom: '100%',
    left: '50%',
    width: 0,
    height: 0,
  },
  tooltipArrowTop: {
    bottom: 'auto',
    top: '100%',
  },

  // Misc
  formContentContainer: {
    paddingBottom: spacing.xl,
  },
  modalSpacer: {
    marginTop: spacing.xl,
  },
  gardenZoomContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    overflow: 'hidden',
  },
  touchDragPreview: {
    position: 'absolute',
    width: 25,
    height: 25,
    pointerEvents: 'none',
    zIndex: zIndex.tooltip,
    opacity: 0.8,
  },
  touchDragPreviewImage: {
    width: 25,
    height: 25,
    resizeMode: 'contain',
  },
  hiddenDragImage: {
    position: 'absolute',
    left: -100,
    top: -100,
    width: 25,
    height: 25,
    pointerEvents: 'none',
    opacity: 1,
  },
  hiddenDragImageImg: {
    width: 25,
    height: 25,
    display: 'block',
  },
  droppedItemContainer: {
    position: 'absolute',
    zIndex: zIndex.dropdown,
  },
  droppedItemContainerEditing: {
    zIndex: zIndex.sticky,
  },
  droppedItemInner: {
    position: 'relative',
    left: 0,
    top: 0,
    transform: 'none',
  },
});
